name: fp_ads
description: "A policy-compliant Google Mobile Ads (AdMob) suite for Flutter with offline fallbacks, reactive ad-free mode, and zero DI lock-in."
version: 0.0.1
homepage: https://prakashbahadurchand.com.np
repository: https://github.com/prakashbahadurchand/flutter_ads
issue_tracker: https://github.com/prakashbahadurchand/flutter_ads/issues

topics:
  - admob
  - google-mobile-ads
  - ads
  - monetization
  - banner-ads

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^9.1.0
  internet_connection_checker_plus: ^3.1.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
